image: node:16.15.0-alpine
cache:
  paths:
    - node_modules/

before_script:
  - npm install hexo-cli -g
  - npm install

pages:
  script:
    - hexo g
  artifacts:
    paths:
      - public
  only:
    - master
