version: 4.0.0
variant: default
# logo: ./img/logo.png

# 页面head标签配置
head:
    favicon: /img/favicon.svg
    manifest:
        name: 听风合笙博客
        short_name: yankai's blog
        start_url: https://yankaizhang.com
        theme_color:
        background_color:
        display: standalone
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''

# 页面头部配置
navbar:
    menu:
        主页: /
        分类: /categories
        标签: /tags
        文章归档: /archives
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/dzzhyk'

# 页面底部配置
footer:
    links:
        渝ICP备20009371号-1:
            url: 'http://beian.miit.gov.cn/'

# 文章配置
article:
    highlight:
        theme: monokai
        clipboard: true
        fold: unfolded
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: 'https://creativecommons.org/licenses/by-nc/4.0/'

search:
    type: insight

sidebar:
    left:
        sticky: true
    right:
        sticky: false

widgets:
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 5
    -
        position: left
        type: recent_posts

# 插件配置
plugins:
    animejs: true
    back_to_top: true
    # Baidu Analytics plugin settings
    # https://tongji.baidu.com
    baidu_analytics:
        # Baidu Analytics tracking ID
        tracking_id:
    # CNZZ statistics
    # https://www.umeng.com/web
    cnzz:
        # CNZZ tracker id
        id:
        # CNZZ website id
        web_id:
    gallery: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        tracking_id:
    # Show a progress bar at top of the page on page loading
    progressbar: true

# CDN 设置
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: fontawesome